/* tslint:disable */
require("./AbsenceRegistration.module.css");
const styles = {
  absenceRegistration: 'absenceRegistration_ff5c4c7a',
  headerBar: 'headerBar_ff5c4c7a',
  headerActions: 'headerActions_ff5c4c7a',
  headerButton: 'headerButton_ff5c4c7a',
  saveButton: 'saveButton_ff5c4c7a',
  headerRight: 'headerRight_ff5c4c7a',
  statusSection: 'statusSection_ff5c4c7a',
  statusBadgeLarge: 'statusBadgeLarge_ff5c4c7a',
  draft: 'draft_ff5c4c7a',
  pending: 'pending_ff5c4c7a',
  approved: 'approved_ff5c4c7a',
  rejected: 'rejected_ff5c4c7a',
  logoSection: 'logoSection_ff5c4c7a',
  logo: 'logo_ff5c4c7a',
  logoText: 'logoText_ff5c4c7a',
  tabs: 'tabs_ff5c4c7a',
  'is-selected': 'is-selected_ff5c4c7a',
  tabContent: 'tabContent_ff5c4c7a',
  formSection: 'formSection_ff5c4c7a',
  sectionTitle: 'sectionTitle_ff5c4c7a',
  formRow: 'formRow_ff5c4c7a',
  formField: 'formField_ff5c4c7a',
  required: 'required_ff5c4c7a',
  fullWidth: 'fullWidth_ff5c4c7a',
  employeeDisplay: 'employeeDisplay_ff5c4c7a',
  avatar: 'avatar_ff5c4c7a',
  initials: 'initials_ff5c4c7a',
  name: 'name_ff5c4c7a',
  fieldValue: 'fieldValue_ff5c4c7a',
  fieldError: 'fieldError_ff5c4c7a',
  errorMessage: 'errorMessage_ff5c4c7a',
  errorIcon: 'errorIcon_ff5c4c7a',
  daysDisplay: 'daysDisplay_ff5c4c7a',
  daysValue: 'daysValue_ff5c4c7a',
  infoIcon: 'infoIcon_ff5c4c7a',
  absenceTypeGroup: 'absenceTypeGroup_ff5c4c7a',
  notesField: 'notesField_ff5c4c7a',
  infoMessage: 'infoMessage_ff5c4c7a',
  adminSection: 'adminSection_ff5c4c7a',
  adminLabel: 'adminLabel_ff5c4c7a',
  buttonRow: 'buttonRow_ff5c4c7a',
  errorBanner: 'errorBanner_ff5c4c7a',
  statusBadge: 'statusBadge_ff5c4c7a',
  actionButtons: 'actionButtons_ff5c4c7a',
  emptyState: 'emptyState_ff5c4c7a',
  emptyIcon: 'emptyIcon_ff5c4c7a',
  emptyText: 'emptyText_ff5c4c7a',
  loadingContainer: 'loadingContainer_ff5c4c7a',
  registrationsHeader: 'registrationsHeader_ff5c4c7a',
  balanceCard: 'balanceCard_ff5c4c7a',
  balanceCardHeader: 'balanceCardHeader_ff5c4c7a',
  balanceIcon: 'balanceIcon_ff5c4c7a',
  infoIconSmall: 'infoIconSmall_ff5c4c7a',
  balanceCardContent: 'balanceCardContent_ff5c4c7a',
  balanceCardLoading: 'balanceCardLoading_ff5c4c7a',
  balanceCardEmpty: 'balanceCardEmpty_ff5c4c7a',
  balanceCardError: 'balanceCardError_ff5c4c7a',
  balanceSection: 'balanceSection_ff5c4c7a',
  balanceSectionTitle: 'balanceSectionTitle_ff5c4c7a',
  balanceRow: 'balanceRow_ff5c4c7a',
  balanceItem: 'balanceItem_ff5c4c7a',
  balanceLabel: 'balanceLabel_ff5c4c7a',
  balanceValue: 'balanceValue_ff5c4c7a',
  primary: 'primary_ff5c4c7a',
  negative: 'negative_ff5c4c7a',
  balanceTransferInfo: 'balanceTransferInfo_ff5c4c7a',
  balanceWarning: 'balanceWarning_ff5c4c7a',
  balanceInfo: 'balanceInfo_ff5c4c7a',
  balanceSuccess: 'balanceSuccess_ff5c4c7a',
  modalContainer: 'modalContainer_ff5c4c7a'
};

export default styles;
/* tslint:enable */